name: Build .NET Core App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x  # Adjust to your desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore Uploaders.sln

      - name: Build
        run: dotnet build Uploaders.sln --configuration Release --no-restore
